<?php

namespace App\Enums;

enum KycDocumentWorkflowErrorCode: string
{
    case INVALID_TRANSITION = 'KYC_DOCUMENT_TRANSITION_INVALID';
    case FORBIDDEN_ACTOR = 'KYC_DOCUMENT_ACTOR_UNAUTHORIZED';
    case SELF_REVIEW = 'KYC_DOCUMENT_SELF_REVIEW';
    case REASON_REQUIRED = 'KYC_DOCUMENT_REASON_REQUIRED';
    case REASON_TOO_LONG = 'KYC_DOCUMENT_REASON_TOO_LONG';
    case REASON_CODE_INVALID = 'KYC_DOCUMENT_REASON_CODE_INVALID';
    case EXPIRY_NOT_REACHED = 'KYC_DOCUMENT_EXPIRY_NOT_REACHED';
}
