<?php

namespace App\Enums;

enum KycImageProcessingErrorCode: string
{
    case PROCESSING_DISABLED = 'KYC_IMAGE_PROCESSING_DISABLED';
    case MASTER_UNSUPPORTED = 'KYC_IMAGE_MASTER_UNSUPPORTED';
    case MASTER_NOT_FOUND = 'KYC_IMAGE_MASTER_NOT_FOUND';
    case INVALID = 'KYC_IMAGE_INVALID';
    case PIXEL_LIMIT_EXCEEDED = 'KYC_IMAGE_PIXEL_LIMIT_EXCEEDED';
    case DECODE_FAILED = 'KYC_IMAGE_DECODE_FAILED';
    case ENCODE_FAILED = 'KYC_IMAGE_ENCODE_FAILED';
    case STORAGE_FAILED = 'KYC_IMAGE_STORAGE_FAILED';
}
