<?php

namespace App\Enums;

enum KycWorkflowErrorCode: string
{
    case INVALID_TRANSITION = 'KYC_TRANSITION_INVALID';
    case FORBIDDEN_ACTOR = 'KYC_ACTOR_UNAUTHORIZED';
    case SELF_REVIEW_FORBIDDEN = 'KYC_SELF_REVIEW';
    case REVIEWER_IS_SUBMITTER = 'KYC_REVIEWER_IS_SUBMITTER';
    case NOT_CURRENT_REVIEWER = 'KYC_REVIEWER_INVALID';
    case REQUIRED_DOCUMENT_MISSING = 'KYC_DOCUMENT_REQUIREMENT_MISSING';
    case REQUIRED_DOCUMENT_NOT_ACCEPTED = 'KYC_DOCUMENT_NOT_ACCEPTED';
    case REQUIRED_DOCUMENT_EXPIRED = 'KYC_DOCUMENT_EXPIRED';
    case SUBMISSION_REQUIREMENTS_UNDEFINED = 'SUBMISSION_REQUIREMENTS_UNDEFINED';
    case REASON_REQUIRED = 'KYC_REASON_REQUIRED';
    case REASON_TOO_LONG = 'KYC_REASON_TOO_LONG';
    case REASON_CODE_INVALID = 'KYC_REASON_CODE_INVALID';
    case RISK_UNCHANGED = 'KYC_RISK_UNCHANGED';
}
